# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, dataDefaultClass, helics, vault, wai }:

cabal.mkDerivation (self: {
  pname = "helics-wai";
  version = "0.5.0";
  sha256 = "1d1kaik2aj0vnln4nbj958d7ay7adb6l62fx606y7xlp7zyhysr4";
  isLibrary = true;
  isExecutable = true;
  buildDepends = [ dataDefaultClass helics vault wai ];
  meta = {
    homepage = "https://github.com/philopon/helics";
    description = "New Relic® agent SDK wrapper for wai";
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };
})
