# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, binary, blazeHtml, blazeMarkup, cmdargs, cryptohash
, dataDefault, deepseq, filepath, fsnotify, httpConduit, httpTypes
, lrucache, mtl, network, networkUri, pandoc, pandocCiteproc
, parsec, random, regexBase, regexTdfa, snapCore
, snapServer, systemFilepath, tagsoup, text, time
, HUnit, QuickCheck, testFramework, testFrameworkHunit, testFrameworkQuickcheck2, utillinux
# , Cocoa, AppKit, CoreData
}:

cabal.mkDerivation (self: {
  pname = "hakyll";
  version = "4.6.4.0";
  sha256 = "0jj1kl9qrv38aavc25cglw90dpaqjznnnvibx9xrni57cj12y95j";
  isLibrary = true;
  isExecutable = true;
  doCheck = false;
  buildDepends = [
    binary blazeHtml blazeMarkup cmdargs cryptohash dataDefault deepseq
    filepath fsnotify httpConduit httpTypes lrucache mtl network
    networkUri pandoc pandocCiteproc parsec random regexBase regexTdfa
    snapCore snapServer systemFilepath tagsoup text time
  # ] ++ self.stdenv.lib.optionals self.stdenv.isDarwin [
  #   Cocoa AppKit CoreData
  ];
  testDepends = [
    /* binary blazeHtml blazeMarkup cmdargs cryptohash dataDefault deepseq */
    /* filepath fsnotify httpConduit httpTypes HUnit lrucache mtl network */
    /* networkUri pandoc pandocCiteproc parsec QuickCheck random regexBase */
    /* regexTdfa snapCore snapServer systemFilepath tagsoup testFramework */
    /* testFrameworkHunit testFrameworkQuickcheck2 text time utillinux */
  ];
  meta = {
    homepage = "http://jaspervdj.be/hakyll";
    description = "A static website compiler library";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
