" vim:ft=vim

set backspace=indent,start
set completeopt=menuone
set encoding=utf-8
set hlsearch
set list
set number
set relativenumber
set splitright

set expandtab shiftwidth=4 tabstop=4
set listchars=tab:»·,trail:·,extends:⟩,precedes:⟨

set scrolloff=8

set lazyredraw
set ttyfast

set backup
set backupdir=~/.vim/tmp/backup//
set backupskip=/tmp/*,/private/tmp/*
set directory=~/.vim/tmp/swap/
set noswapfile
set undodir=~/.vim/tmp/undo//
set undofile

if !isdirectory(expand(&undodir))
  call mkdir(expand(&undodir), "p")
endif
if !isdirectory(expand(&backupdir))
  call mkdir(expand(&backupdir), "p")
endif
if !isdirectory(expand(&directory))
  call mkdir(expand(&directory), "p")
endif

command! -bang -nargs=* Ag call fzf#vim#ag(<q-args>,
      \ <bang>0 ? fzf#vim#with_preview('up:30%')
      \ : fzf#vim#with_preview('right:50%:hidden', '?'),
      \ <bang>0)

command! -bang -nargs=* Rg call fzf#vim#grep(
      \ 'rg --column --line-number --no-heading --color=always '.shellescape(<q-args>), 1,
      \ <bang>0 ? fzf#vim#with_preview('up:30%')
      \         : fzf#vim#with_preview('right:50%:hidden', '?'),
      \ <bang>0)

inoremap <C-g> <Esc><CR>
vnoremap <C-g> <Esc><CR>
cnoremap <C-g> <Esc><CR>

cnoremap %% <C-r>=expand('%:h') . '/'<CR>
nnoremap // :nohlsearch<CR>

vnoremap J :m '>+1<CR>gv=gv
vnoremap K :m '<-2<CR>gv=gv

let mapleader = ' '

nnoremap <Leader><Leader> <C-^>
nnoremap <silent> <Leader>q :cclose<CR> :lclose<CR> :pclose<CR>


" ale
let g:ale_sign_error = '▶'
let g:ale_sign_warning = '--'

let g:is_bash = 1
let g:ale_completion_autoimport = 0
let g:ale_lint_on_text_changed = 'normal'

let g:ale_fixers =
      \ { 'python': ['isort']
      \ , 'rust': ['rustfmt']
      \ }
let g:ale_linters =
      \ { 'cpp': ['ccls']
      \ , 'elixir': ['elixir-ls']
      \ , 'haskell': ['hie']
      \ , 'python': ['pyright', 'pylsp']
      \ , 'rust': ['analyzer']
      \ }
let g:ale_python_pylsp_executable = 'jedi-language-server'

let g:ale_rust_cargo_check_tests = 1
let g:ale_virtualenv_dir_names = ['venv']

nnoremap <silent> <Leader>f :ALEFix<CR>
nnoremap <silent> <Leader>a :ALECodeAction<CR>
nnoremap <silent> <Leader>d :ALEGoToDefinition<CR>
nnoremap <silent> <Leader>D :ALEGoToDefinitionInVSplit<CR>
nnoremap <silent> <Leader>R :ALEFindReferences<CR>
nnoremap <silent> <Leader>k :ALESignature<CR>
nnoremap <silent> <Leader>K :ALEHover<CR>
nnoremap <silent> [a :ALEPreviousWrap<CR>
nnoremap <silent> ]a :ALENextWrap<CR>

" fzf
nnoremap <silent> <Leader>p :FZF<CR>
nnoremap <silent> <Leader>e :exe 'FZF ' . expand('%:h')<CR>
nnoremap <silent> <Leader>b :Buffers<CR>
nnoremap <silent> <Leader>g :GFiles?<CR>
nnoremap <silent> <Leader>r :Rg \b<C-R><C-W>\b<CR>

" vim-dispatch
let g:cargo_makeprg_params = 'check'
let g:dispatch_compilers =
      \ { 'bundle exec': 'ruby'
      \ , 'mix test': 'exunit'
      \ , 'poetry run pytest': 'pytest'
      \ }

" LanguageClient-nvim
let g:LanguageClient_diagnosticsList = 'Location'
let g:LanguageClient_useVirtualText = 0
let g:LanguageClient_serverCommands =
      \ { 'cpp': ['clangd']
      \ , 'elixir': ['elixir-ls']
      \ , 'haskell': ['hie-wrapper']
      \ , 'python': ['pyls']
      \ , 'rust': ['rls']
      \ }

" colors-solarized
" let g:solarized_termcolors=16
" let g:solarized_termtrans=1

" vim-surround
vmap s S

" vim-test
let test#strategy = 'dispatch'
let test#python#runner = 'pytest'
let test#python#pytest#options = {
  \ 'all': '--quiet'
  \ }
nnoremap <Leader>t :TestVisit<CR>
nnoremap T<CR> :TestLast<CR>
nnoremap t<CR> :TestNearest<CR>

" youcompleteme
let g:ycm_seed_identifiers_with_syntax = 1
