# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, attoparsec, network_2_5_0_0, text, yesodRoutes }:

cabal.mkDerivation (self: {
  pname = "route-generator";
  version = "0.6.1";
  sha256 = "0bfrb3mz9nxrl4l5pikrp3x4igq4w9jlmvwikyc71ph8ks6rghc6";
  isLibrary = false;
  isExecutable = true;
  buildDepends = [ attoparsec network_2_5_0_0 text yesodRoutes ];
  meta = {
    homepage = "http://github.com/singpolyma/route-generator";
    description = "Utility to generate routes for use with yesod-routes";
    license = "unknown";
    platforms = self.ghc.meta.platforms;
  };
})
