# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, attoparsec, base64Bytestring, blazeBuilder, Cabal, conduit
, conduitExtra, dataDefaultClass, fileEmbed, filepath, fsnotify
, ghcPaths, httpConduit, httpReverseProxy, httpTypes, liftedBase
, network, optparseApplicative, parsec, projectTemplate, resourcet
, shakespeare, split, streamingCommons, systemFileio
, systemFilepath, tar, text, time, transformers, transformersCompat
, unixCompat, unorderedContainers, wai, waiExtra, warp, yaml, zlib
, Cocoa, AppKit, CoreData
}:

cabal.mkDerivation (self: {
  pname = "yesod-bin";
  version = "1.4.3.6";
  sha256 = "0mha1csljbnh5idwi5hsk86fgqiq5kk1crdhiyyvigysrl83z0py";
  isLibrary = false;
  isExecutable = true;
  buildDepends = [
    attoparsec base64Bytestring blazeBuilder Cabal conduit conduitExtra
    dataDefaultClass fileEmbed filepath fsnotify ghcPaths httpConduit
    httpReverseProxy httpTypes liftedBase network optparseApplicative
    parsec projectTemplate resourcet shakespeare split streamingCommons
    systemFileio systemFilepath tar text time transformers
    transformersCompat unixCompat unorderedContainers wai waiExtra warp
    yaml zlib
  ] ++ self.stdenv.lib.optionals self.stdenv.isDarwin [
    Cocoa AppKit CoreData
  ];
  meta = {
    homepage = "http://www.yesodweb.com/";
    description = "The yesod helper executable";
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };
})
