#!/bin/sh

cd $HOME

[ ! -e .sbin ] && [ -e Dropbox/library/sbin ] && \
  ln -s Dropbox/library/sbin .sbin

[ ! -e .zsh/peat ] && \
  git clone https://github.com/sjl/peat.git .zsh/peat && \
  ln -s .zsh/peat/peat ~/.bin/peat

[ ! -f .vim/autoload/plug.vim ] && \
  mkdir -p ~/.vim/autoload && \
  curl -fLo ~/.vim/autoload/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

[ ! -f ~/.tmux/plugins/tpm ] && \
  mkdir -p ~/.tmux/plugins/tpm && \
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# [ ! -e $HOME/.emacs.d/vendor ] && \
#   mkdir -p $HOME/.emacs.d/vendor

# [ ! -e $HOME/.emacs.d/el-get ] && \
#   git clone https://github.com/dimitri/el-get.git $HOME/.emacs.d/el-get

exit 0
