#!/bin/sh

[ which nvim &> /dev/null ] && \
  ln -s $HOME/.vim $HOME/.nvim

[ ! -e $HOME/.sbin ] && [ -e $HOME/Dropbox/library/sbin ] && \
  ln -s $HOME/Dropbox/library/sbin $HOME/.sbin

[ ! -e $HOME/.zsh/peat ] && \
  git clone https://github.com/sjl/peat.git $HOME/.zsh/peat && \
  ln -s $HOME/.zsh/peat/peat $HOME/.bin/peat

[ ! -f $HOME/.vim/autoload/plug.vim ] && \
  mkdir -p $HOME/.vim/autoload && \
  curl -fLo $HOME/.vim/autoload/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

[ ! -e $HOME/.tmux/plugins/tpm ] && \
  mkdir -p $HOME/.tmux/plugins/tpm && \
  git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm

# [ ! -e $HOME/.emacs.d/vendor ] && \
#   mkdir -p $HOME/.emacs.d/vendor

# [ ! -e $HOME/.emacs.d/el-get ] && \
#   git clone https://github.com/dimitri/el-get.git $HOME/.emacs.d/el-get

exit 0
