#!/bin/sh

[ ! -e $HOME/.share ] && \
  ln -s $(brew --prefix)/share $HOME/.share

[ ! -e $HOME/.zsh/peat ] && \
  git clone https://github.com/sjl/peat.git $HOME/.zsh/peat && \
  ln -s $HOME/.zsh/peat/peat ~/.bin/peat

[ ! -f $HOME/.vim/autoload/plug.vim ] && \
  mkdir -p ~/.vim/autoload && \
  curl -fLo ~/.vim/autoload/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

[ ! -e $HOME/.emacs.d/vendor ] && \
  mkdir -p $HOME/.emacs.d/vendor

[ ! -e $HOME/.emacs.d/el-get ] && \
  git clone https://github.com/dimitri/el-get.git $HOME/.emacs.d/el-get

exit 0
