# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, bytestringShow, dataDefaultClass
# , newrelic-collector-client, newrelic-common, newrelic-transaction
, time
}:

cabal.mkDerivation (self: {
  pname = "helics";
  version = "0.5.0.1";
  sha256 = "0kqmqyf22fjcbsqlbyxmg6238im8kp6baip3v8f7hibkpgyfqip1";
  isLibrary = true;
  isExecutable = true;
  buildDepends = [ bytestringShow dataDefaultClass time ];
  extraLibraries = [
    # TODO: create deriviation
    # newrelic-collector-client newrelic-common newrelic-transaction
  ];
  meta = {
    homepage = "https://github.com/philopon/helics";
    description = "New Relic® agent SDK wrapper for Haskell";
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };
})
